Repository fga-eps-mds/2022-2-Certifik8, pull requests merged in 2023-01, with the labels that each got.

#65 Nova main com remoção do Mkdocs
  GitPages_Mkdocs/docs/assets/icons/folder.ico
  GitPages_Mkdocs/docs/img/Leandrynnho_Professor_holding_a_certificate_in_harvard_c6597855-799e-4236-92ec-bf61d4f931e8.png
  GitPages_Mkdocs/docs/img/folder.ico
  GitPages_Mkdocs/docs/index.md
  GitPages_Mkdocs/docs/overrides/home.html
  GitPages_Mkdocs/docs/overrides/main.html
  GitPages_Mkdocs/docs/pages/index.md
  GitPages_Mkdocs/docs/stylesheets/extra.css
  GitPages_Mkdocs/index.html
  GitPages_Mkdocs/mkdocs.yml
  GitPages_Mkdocs/site/404.html
  GitPages_Mkdocs/site/assets/icons/folder.ico
  GitPages_Mkdocs/site/assets/images/favicon.png
  GitPages_Mkdocs/site/assets/javascripts/bundle.d6c3db9e.min.js
  GitPages_Mkdocs/site/assets/javascripts/bundle.d6c3db9e.min.js.map
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.ar.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.da.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.de.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.du.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.es.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.fi.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.fr.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.hi.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.hu.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.it.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.ja.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.jp.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.ko.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.multi.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.nl.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.no.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.pt.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.ro.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.ru.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.stemmer.support.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.sv.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.ta.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.th.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.tr.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.vi.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/min/lunr.zh.min.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/tinyseg.js
  GitPages_Mkdocs/site/assets/javascripts/lunr/wordcut.js
  GitPages_Mkdocs/site/assets/javascripts/workers/search.16e2a7d4.min.js
  GitPages_Mkdocs/site/assets/javascripts/workers/search.16e2a7d4.min.js.map
  GitPages_Mkdocs/site/assets/stylesheets/main.20d9efc8.min.css
  GitPages_Mkdocs/site/assets/stylesheets/main.20d9efc8.min.css.map
  GitPages_Mkdocs/site/assets/stylesheets/palette.815d1a91.min.css
  GitPages_Mkdocs/site/assets/stylesheets/palette.815d1a91.min.css.map
  GitPages_Mkdocs/site/img/Leandrynnho_Professor_holding_a_certificate_in_harvard_c6597855-799e-4236-92ec-bf61d4f931e8.png
  GitPages_Mkdocs/site/img/folder.ico
  GitPages_Mkdocs/site/index.html
  GitPages_Mkdocs/site/overrides/home.html
  GitPages_Mkdocs/site/overrides/main.html
  GitPages_Mkdocs/site/pages/index.html
  GitPages_Mkdocs/site/search/search_index.json
  GitPages_Mkdocs/site/sitemap.xml
  GitPages_Mkdocs/site/sitemap.xml.gz
  GitPages_Mkdocs/site/stylesheets/extra.css
Labels: refactoring

#66 57 refatorar codigo
  .coveragerc
  .github/workflows/automatizacao.yml
  .github/workflows/linter.yml
  .gitignore
  Certifik8/__init__.py
  Certifik8/constants/__init__.py
  Certifik8/constants/menu.txt
  Certifik8/constants/template.html
  Certifik8/examples/Melissa Ribeiro Araujo.html
  Certifik8/examples/Melissa Ribeiro Araujo.png
  Certifik8/examples/__init__.py
  Certifik8/examples/completa.xlsx
  Certifik8/examples/exemplo-certificados.zip
  Certifik8/examples/sem_coluna_informacoes.xlsx
  Certifik8/examples/sem_decano.xlsx
  Certifik8/examples/tabela_1_reg.xlsx
  Certifik8/examples/vazia.xlsx
  Certifik8/main.py
  Certifik8/modules/__init__.py
  Certifik8/modules/converter/__init__.py
  Certifik8/modules/converter/__pycache__/__init__.cpython-310.pyc
  Certifik8/modules/converter/__pycache__/html2pdf.cpython-310.pyc
  Certifik8/modules/converter/html2pdf.py
  Certifik8/modules/generator/__init__.py
  Certifik8/modules/generator/certificado.py
  Certifik8/modules/handler/__init__.py
  Certifik8/modules/handler/tabela.py
  Certifik8/modules/utils.py
  Certifik8/path.py
  Certifik8/tests/__init__.py
  Certifik8/tests/test_certificado.py
  Certifik8/tests/test_html2pdf.py
  Certifik8/tests/test_tabela.py
  Certifik8/tests/test_utils.py
  Makefile
  docs/exemplo/exemplo1.xlsx
  docs/exemplo/exemplo2.xlsx
  pyproject.toml
  src/Certifik8/data_emissao.py
  src/Certifik8/html2pdf.py
  src/Certifik8/main.py
Labels: bug, enhancement, Epic, refactoring

#70 Alterações de estilo e interatividade com usuário
  .coveragerc
  .gitignore
  Certifik8/main.py
  Certifik8/modules/converter/__pycache__/__init__.cpython-310.pyc
  Certifik8/modules/converter/__pycache__/html2pdf.cpython-310.pyc
  Certifik8/modules/converter/html2pdf.py
  Certifik8/modules/generator/certificado.py
  Certifik8/modules/handler/tabela.py
  Certifik8/modules/selector/__init__.py
  Certifik8/modules/selector/file_selection.py
  Certifik8/modules/selector/folder_selection.py
  Certifik8/tests/test_certificado.py
  Certifik8/tests/test_html2pdf.py
  Certifik8/tests/test_tabela.py
  Certifik8/tests/test_utils.py
Labels: enhancement, Feature
